<?php
namespace ItsLaivy\DataAPI\Modules\SQL;

use ItsLaivy\DataAPI\Modules\Database;
use ItsLaivy\DataAPI\Modules\DatabaseType;
use Symfony\Component\Console\Helper\Table;

abstract class SQLDatabase extends Database {

    private readonly array $tables;

    public function __construct(SQLDatabaseType $databaseType, string $name) {
        parent::__construct($databaseType, $name);

        $this->tables = array();
    }

    public function getDatabaseType(): SQLDatabaseType {
        return parent::getDatabaseType(); // TODO: Change the autogenerated stub
    }

    /**
     * @return Table[]
     */
    public function getTables(): array {
        return $this->tables;
    }

}