<?php
namespace ItsLaivy\DataAPI\Modules\SQL;

use Exception;
use ItsLaivy\DataAPI\Modules\Database;
use ItsLaivy\DataAPI\Modules\Variable;

class SQLVariable extends Variable {

    /**
     * @var SQLTable[][]
     */
    public static array $SQL_VARIABLES = array();

    public static function getSQLVariable(SQLTable $table, string $name): Variable|null {
        if (array_key_exists($table->getIdentification(), self::$SQL_VARIABLES)) {
            foreach (self::$SQL_VARIABLES[$table->getIdentification()] as $variable) {
                if ($variable->getName() == $name) {
                    return $variable;
                }
            }
        }
        return null;
    }

    private readonly SQLTable $table;

    public function __construct(SQLTable $table, string $name, mixed $default, bool $serialize = true, bool $temporary = false) {
        $keys = array("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","_");
        foreach (str_split($name) as $char) {
            foreach ($keys as $allowed) {
                if ($char == $allowed) {
                    continue 2;
                }
            }
            throw new exception("Illegal character in the variable's name: '".$name."'");
        }

        // ----/-/---- //

        $this->table = $table;
        parent::__construct($table->getDatabase(), $name, $default, $serialize, $temporary);

        $this->getTable()->getVariables()[$name] = $this;

        if (!array_key_exists($table->getIdentification(), self::$SQL_VARIABLES)) {
            self::$SQL_VARIABLES[$table->getIdentification()] = array();
        }
        self::$SQL_VARIABLES[$table->getIdentification()][] = $this;
    }

    /**
     * @return SQLTable
     */
    public function getTable(): SQLTable {
        return $this->table;
    }

    public function delete(): void {
        unset($this->getTable()->getVariables()[$this->getName()]);
        unset(self::$SQL_VARIABLES[$this->getTable()->getIdentification()][array_search($this->getName(), self::$SQL_VARIABLES)]);
        parent::delete(); // TODO: Change the autogenerated stub
    }

}